version: '3'
services:

### Nginx
    nginx:
        image: nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./conf/nginx:/etc/nginx/conf.d
            - ./conf/certs:/etc/nginx/certs
            - ./src:/var/www/html
            - ./logs/nginx:/var/log/nginx
        links:
            - php

### PHP
    php:
        image: php:fpm
        links:
           - db
        volumes:
            - ./src:/var/www/html
            - ./conf/php:/usr/local/etc/php/conf.d
            - ./logs/php:/var/log/php
        environment:
            APP_DEBUG: "true"

### DB:Postgres
    db:
        image: postgres
        ports:
            - "5432:5432"
        volumes:
            - ./postgres/pgdata:/var/lib/postgresql/data/pgdata
            - ./conf/postgres/my-postgres.conf:/etc/postgresql/postgresql.conf
#            - ./conf/mariadb/:/etc/mysql/conf.d
#            - ./logs/mariadb:/var/log/mysql
        environment:
            PGDATA: /var/lib/postgresql/data/pgdata
            POSTGRES_PASSWORD: secret

### Adminer
    adminer:
        image: adminer
        restart: always
        ports:
            - "8080:8080"
        environment:
          ADMINER_DEFAULT_SERVER: db
